apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/version: latest
  name: observatorium-api
data:
  rbac.yaml: |-
    "roleBindings":
    - "name": "telemeter"
      "roles":
      - "read-write"
      "subjects":
      - "kind": "user"
        "name": "admin@example.com"
    "roles":
    - "name": "read-write"
      "permissions":
      - "read"
      - "write"
      "resources":
      - "metrics"
      "tenants":
      - "telemeter"
  tenants.yaml: |-
    "tenants":
    - name: telemeter
      id: FB870BF3-9F3A-44FF-9BF7-D7A047A52F43
      oidc:
        clientID: telemeter
        clientSecret: test
        issuerURL: http://127.0.0.1:5556/dex
        redirectURL: http://localhost:8080/oidc/telemeter/callback
        usernameClaim: email
