resources:
- ../../crd
- ../../rbac
- ../../manager

# Adds namespace to all resources.
namespace: default

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: loki-operator-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue
commonLabels:
  app.kubernetes.io/name: loki-operator
  app.kubernetes.io/instance: loki-operator-v0.0.1
  app.kubernetes.io/version: "0.0.1"
  app.kubernetes.io/part-of: cluster-logging
  app.kubernetes.io/managed-by: operator-lifecycle-manager
