tenants:
{{- if eq .Stack.Tenants.Mode "static" -}}
{{- range $spec := .Stack.Tenants.Authentication }}
- name: {{ $spec.Name }}
  id: {{ $spec.ID }}
  oidc:
    issuerURL: {{ $spec.OIDC.IssuerURL }}
    redirectURL: {{ $spec.OIDC.RedirectURL }}
    {{ if $spec.OIDC.UsernameClaim }}
    usernameClaim: {{ $spec.OIDC.UsernameClaim }}
    {{- end -}}
    {{ if $spec.OIDC.GroupClaim }}
    groupClaim: {{ $spec.OIDC.GroupClaim }}
    {{- end -}}
{{- end -}}
{{- else if eq .Stack.Tenants.Mode "dynamic" -}}
{{- if $tenant := .Stack.Tenants -}}
{{- range $spec := $tenant.Authentication }}
- name: {{ $spec.Name }}
  id: {{ $spec.ID }}
  oidc:
    issuerURL: {{ $spec.OIDC.IssuerURL }}
    redirectURL: {{ $spec.OIDC.RedirectURL }}
    {{ if $spec.OIDC.UsernameClaim }}
    usernameClaim: {{ $spec.OIDC.UsernameClaim }}
    {{- end -}}
    {{ if $spec.OIDC.GroupClaim }}
    groupClaim: {{ $spec.OIDC.GroupClaim }}
    {{- end -}}
  {{ print "\n" }}
  opa:
    url: {{ $tenant.Authorization.OPA.URL }}
{{- end -}}
{{- end -}}
{{- else -}}
{{ print "\n" }}
- name: application
  id: 32e45e3e-b760-43a2-a7e1-02c5631e56e9
  oidc:
    clientID: test
    clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
    issuerCAPath: ./tmp/certs/ca.pem
    issuerURL: https://127.0.0.1:5556/dex
    redirectURL: https://localhost:8443/oidc/application/callback
    usernameClaim: name
  opa:
    url: http://127.0.0.1:8080/v1/data/observatorium/allow
- name: infrastructure
  id: 40de0532-10a2-430c-9a00-62c46455c118
  oidc:
    clientID: test
    clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
    issuerCAPath: ./tmp/certs/ca.pem
    issuerURL: https://127.0.0.1:5556/dex
    redirectURL: https://localhost:8443/oidc/infrastructure/callback
    usernameClaim: name
  opa:
    url: http://127.0.0.1:8080/v1/data/observatorium/allow
- name: audit
  id: 26d7c49d-182e-4d93-bade-510c6cc3243d
  oidc:
    clientID: test
    clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
    issuerCAPath: ./tmp/certs/ca.pem
    issuerURL: https://127.0.0.1:5556/dex
    redirectURL: https://localhost:8443/oidc/audit/callback
    usernameClaim: name
  opa:
    url: http://127.0.0.1:8080/v1/data/observatorium/allow
{{- end -}}
