apiVersion: v1
imagePullSecrets:
- name: logfile-metric-dockercfg
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: cluster-logging
    app.kubernetes.io/version: 0.0.1
  name: loki-operator-logfile-metric
secrets:
- name: logfile-metric-dockercfg
- name: logfile-metric-token
