apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: loki-operator-logfile-metrics
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: cluster-logging
    app.kubernetes.io/version: 0.0.1
    name: log-file-metric-exporter
  name: loki-operator-log-file-metric-exporter-http-service
spec:
  ports:
  - name: logfile-metrics
    port: 2112
    protocol: TCP
    targetPort: logfile-metrics
  selector:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: cluster-logging
    app.kubernetes.io/version: 0.0.1
    name: log-file-metric-exporter
status:
  loadBalancer: {}
