apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: cluster-logging
    app.kubernetes.io/version: 0.0.1
  name: loki-operator-logfile-metric-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-operator-logfile-metric-privileged
subjects:
- kind: ServiceAccount
  name: loki-operator-logfile-metric
  namespace: openshift-logging
