apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: cluster-logging
    app.kubernetes.io/version: 0.0.1
  name: loki-operator-logfile-metric-privileged
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - logfile-metric-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
