apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: cluster-logging
    app.kubernetes.io/version: 0.0.1
    name: log-file-metric-exporter
  name: loki-operator-monitor-log-file-metric-exporter
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    port: logfile-metrics
    scheme: https
    scrapeTimeout: 10s
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: loki-operator-log-file-metric-exporter-http-service.openshift-logging.svc
  selector:
    matchLabels:
      name: log-file-metric-exporter
