updates:
  - file: "{MAJOR}.{MINOR}/cluster-logging.v{MAJOR}.{MINOR}.0.clusterserviceversion.yaml" # relative to this file
    update_list:
    # replace metadata.name value
    - search: "loki-operator.v{MAJOR}.{MINOR}.0"
      replace: "loki-operator.{FULL_VER}"
    # replace entire version line, otherwise would replace 4.2.0 anywhere
    - search: "version: {MAJOR}.{MINOR}.0"
      replace: "version: {FULL_VER}"
    - search: 'olm.skipRange: ">=4.6.0-0 <{MAJOR}.{MINOR}.0"'
      replace: 'olm.skipRange: ">=4.6.0-0 <{FULL_VER}"'
  - file: "loki-operator.package.yaml"
    update_list:
    - search: "currentCSV: loki-operator.v{MAJOR}.{MINOR}.0"
      replace: "currentCSV: loki-operator.{FULL_VER}"
