# This patch inject a sidecar container which is a HTTP proxy for the
# controller manager, it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - command: ["go run"]
          name: manager
          args:
          - "--with-ocp-mode"
          - "--with-service-monitors"
          - "--with-tls-service-monitors"
