# This patch inject a sidecar container which is a HTTP proxy for the
# controller manager, it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
          - "--with-lokistack-gateway"
          - "--with-cert-signing-service"
          - "--with-service-monitors"
          - "--with-tls-service-monitors"
