---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: logfile-metric-scc
allowPrivilegedContainer: true
requiredDropCapabilities:
  - MKNOD
  - CHOWN
  - DAC_OVERRIDE
  - FSETID
  - FOWNER
  - SETGID
  - SETUID
  - SETPCAP
  - NET_BIND_SERVICE
  - KILL
allowHostDirVolumePlugin: true
allowHostPorts: false
runAsUser:
  type: RunAsAny
users: []
allowHostIPC: false
seLinuxContext:
  type: RunAsAny
readOnlyRootFilesystem: false
fsGroup:
  type: RunAsAny
groups:
  - 'system:cluster-admins'
defaultAddCapabilities: null
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowedCapabilities: null
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: logfile-metric
secrets:
  - name: logfile-metric-dockercfg
  - name: logfile-metric-token
imagePullSecrets:
  - name: logfile-metric-dockercfg
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logfile-metric-privileged
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - logfile-metric-scc
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logfile-metric-privileged-binding
subjects:
  - kind: ServiceAccount
    name: logfile-metric
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logfile-metric-privileged
---
apiVersion: v1
kind: Service
metadata:
  name: log-file-metric-exporter-http-service
  labels:
    name: log-file-metric-exporter
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: loki-operator-logfile-metrics
spec:
  ports:
    - name: logfile-metrics
      port: 2112
      protocol: TCP
      targetPort: logfile-metrics
  selector:
    name: log-file-metric-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-log-file-metric-exporter
  labels:
    name: log-file-metric-exporter
spec:
  selector:
    matchLabels:
      name: log-file-metric-exporter
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      path: /metrics
      port: logfile-metrics
      scheme: https
      interval: 30s
      scrapeTimeout: 10s
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: loki-operator-log-file-metric-exporter-http-service.openshift-logging.svc
