kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logfile-metric-privileged
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - logfile-metric-scc
