# This patch inject a sidecar container which is a HTTP proxy for the
# controller manager, it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
          - name: RELATED_IMAGE_LOKI
            value: docker.io/grafana/loki:2.2.0
          - name: RELATED_IMAGE_OPA
            value: quay.io/observatorium/opa-openshift:latest
